### ISSUE TITLE
Infinite Loop fix

### ISSUE THREAD

**Issue by Mistik** [SpanksMcYeet/aps-plus#1]
I found an infinite loop issue in this server 

In the file collisionfunctions.js

Change
`    while (dist <= my.realSize + n.realSize && !(strike1 && strike2)) {`

to

`  let cycles = 0;
     while (dist <= my.realSize + n.realSize && !(strike1 && strike2) && cycles < 150) {
     cycles += 1;`

**Comment by TGS5994** [comment]
Implemented.
